language: node_js
node_js:
  - node
script:
- npm install
- npm install -g serve > /dev/null
- serve -p 3000 > /dev/null &
- sleep 1
- curl -s -L https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 > file.tar.bz2
- bzip2 -d file.tar.bz2
- tar -xf file.tar
- ./phantomjs-2.1.1-linux-x86_64/bin/phantomjs test/phantom-runner.js
